# This file was generated by GoReleaser. DO NOT EDIT.
class TokenCli < Formula
  desc "OpenID token generator"
  homepage "https://github.com/imduffy15/token-cli"
  url "https://github.com/imduffy15/token-cli/releases/download/v0.0.6/token-cli_macOS_amd64.tar.gz"
  version "0.0.6"
  sha256 "7a016399aeb4df2a2eec3694bb7d3236a8d392237e59b01e4af795092e821eb3"

  def install
    bin.install "token-cli"
  end
end
